# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           http://stanford.edu/group/stanford_atlas
relative_permalinks: http://stanford.edu/group/stanford_atlas

# Setup
title:               Stanford ATLAS
tagline:             'Fast TracKer, Higgs Physics and More'
description:         'An experimental particle physics group at the energy frontier'
url:                 http://stanford.edu/group/stanford_atlas
baseurl:             http://stanford.edu/group/stanford_atlas
#url:                 ''
#baseurl:             ''

paginate:            5

# About/contact
author:
  name:              Lauren Tompkins
  url:               https://physics.stanford.edu/people/faculty/lauren-tompkins
  email:             laurenat@stanford.edu

# Custom vars
version:             1.0.0
